title: "Giannis Anthis"
email: asofoklis1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My portofolio
baseurl: "/" 
url: "/website" 
twitter_username: Drosaditis
github_username:  Drosaditis

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
